#!/usr/bin/env python
'''
    Setup script for TG-Cellular-Automation calculations.
  
   
    Written by Carlos A. Gimenez, Natural and Exact Science Faculty
                                  Northeastern University of Argentina,
        			              Corrientes, Argentina
   
'''
import sys
import os.path as path

if sys.version < '2.4':
    print('pam requires python version >= 2.4')
    sys.exit(1)

class prepare_kernel:
  """
  Set the kernel code
  """
   self.build_path = os.getcwd()+"/src/tg_kernel/bin"

   def __init__(self):

      import src.tg_kernel.build as setenv 

      if os.path.exists(self.build_path):

         setenv.set_enviroment().__clean__()

      else:

         setenv.set_enviroment().__install__()

prepare_kernel()
