#!/usr/bin/env python
'''
@author: Carlos A. Gimenez
 
'''
import sys

if sys.version < '2.4':
    print('pam requires python version >= 2.4')
    sys.exit(1)

class prepare_kernel:
  """
  Set the kernel code
  """
  def __init__(self):
    import src.tg_kernel.build as setenv 
    setenv.set_enviroment().__install__()

prepare_kernel()
