#!/usr/bin/env python

"""
    Setup script for TG-Cellular-Automation calculations.
  
   
    Written by Carlos A. Gimenez, Natural and Exact Science Faculty
                                  Northeastern University of Argentina,
        			              Corrientes, Argentina
   
    Contributors: --
   
    Environment variables used by pam:
             DIRTIMEOUT        - time out limit for TG-Cellular-Automation run
          
"""
 
import os
import sys

if sys.version < '2.4':
    print('pam requires python version >= 2.4')
    sys.exit(1)

class set_enviroment:
  """
  class for handling the  TG-Cellular-Automation setup
  """
  def __init__(self):
    """
    Initialize the global set of variables
    """
    src = os.getcwd() 
    os.system("cmake -DCMAKE_BUILD_TYPE=RELEASE")
    print "runing cmake"
    os.system("make")
    print "done"

print "The TG-Cellular-Automation code is ready, enjoy your meal"
