#!/usr/bin/env python

"""
    tgrun script for TG-Cellular-Automation calculations.
  
   
    Written by Carlos A. Gimenez, Natural and Exact Science Faculty
                                  Northeastern University of Argentina,
        			              Corrientes, Argentina
   
             DIRTIMEOUT        - time out limit for TG-Cellular-Automation run
          
"""
 
import os
import sys

class tg_run:
  """
  class for handling the  TG-Cellular-Automation setup
  """
  def __init__(self):
    """
    Initialize the global set of variables
    """
    os.system("cmake -P distclean.cmake")
    print "runing cmake clean"
    os.system("make distclean")
    print "done"

print "The TG-Cellular-Automation code is ready, enjoy your meal"
